### ISSUE TITLE
EcoMax920 missing state

### ISSUE THREAD

**Issue by svenlange2** [denpamusic/homeassistant-plum-ecomax#10]
This device (EcoMax920) reports mode '7' that is "Buring off" (state when the burner switches off and cleans itself - takes like 10 minutes to complete) according to device display. I already added it manually to my setup but it gets wiped out by updates. Maybe add in the future ? Right now it displays "Unknown" in Hass.

**Comment by denpamusic** [comment]
Thank you very much for your contribution!
Burning off state added.

I'll also consider adding additional numeric sensor that shows state as a number, so that users can use hass'es [template integration](https://www.home-assistant.io/integrations/template/) to name states themselves.
