### ISSUE TITLE
USR-TCP232-304 device support

### ISSUE THREAD

**Issue by mihai198202** [denpamusic/homeassistant-plum-ecomax#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [X] support for a new product
- [ ] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

Hello i have mistakenly bought the USR-TCP232-304
Is this supported ? If not then are you planning to include it on the list ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mihai198202** [comment]
I see that there is support for the device will open an issue

**Comment by mihai198202** [comment]
Closing

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!

USR-TCP232-304 is a proper RS485 to Ethernet converter, and as such, it should work fine. In fact, there's no need to explicitly support specific models for such converters in the integration. As long as it's advertised as RS485 to Ethernet/WiFi/USB it will work.
Just make sure to connect both signal lines (A, B) __and__ G(GND).

You can learn about connection scheme [here](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/9#issuecomment-1336140374).

I plan on adding this information to the documentation before next release, to prevent future confusion.

**Comment by mihai198202** [comment]
@denpamusic just opened another issue  as i saw the device indeed is supported.
