### ISSUE TITLE
One of thermostats unavailable

### ISSUE THREAD

**Issue by danielkovarik2** [denpamusic/homeassistant-plum-ecomax#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Hello, today my thermostats became unavailable. I see following in logs:

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:361
integration: Climate (documentation, issues)
First occurred: 1:06:13 PM (1 occurrences)
Last logged: 1:06:13 PM

Error while setting up plum_ecomax platform for climate
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/event_manager.py", line 37, in __getattr__
    return self.data[name]
           ~~~~~~~~~^^^^^^
KeyError: 'thermostats'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/plum_ecomax/climate.py", line 250, in async_setup_entry
    for index in connection.device.thermostats
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/event_manager.py", line 39, in __getattr__
    raise AttributeError from e
AttributeError: . Did you mean: '_thermostats'?


### I have following devices connected:

- [ ] ecoMAX 3xx series
- [ ] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

_No response_

### My diagnostics data:

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danielkovarik2** [comment]
Update, now both are unavailable

**Comment by danielkovarik2** [comment]
Apologies, didn't notice hw connection issue

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!

No problem! I was about to comment, that if you didn't install any updates today, thiis most likely hw issue. I'll make an error log message a bit more clear.
