### ISSUE TITLE
buffer temperature (top-bottom) support

### ISSUE THREAD

**Issue by jwhnat** [denpamusic/homeassistant-plum-ecomax#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [ ] support for a new product
- [X] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

Hello Friend.

I wanted to ask if you would add the ability to read the temperature of "buffer top" and "buffer bottom"?
My controller is ecoMAX850 and I have extended module B (buffer support)

Thank you for your time.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thanks for your suggestion!

Could you please download diagnostic data for your device as described [here](https://www.home-assistant.io/integrations/diagnostics/) and attach it to this issue or <a href="mailto:denpa@denpa.pro?subject=ecoMAX 850p diagnostic data">send it to me via email</a>, so I can make sure, that values for `upper_buffer_temp` and `lower_buffer_temp` are present in your device data and are correctly parsed by underlying PyPlumIO library.

Thank you beforehand!

**Comment by jwhnat** [comment]
Yes of course, I've attached the file. Will there be more options?

niedz., 15 sty 2023, 23:52 użytkownik Denis Paavilainen <
***@***.***> napisał:

**Comment by jwhnat** [comment]
Hello, when will it be possible to test buffer temperatures?

**Comment by denpamusic** [comment]
You could've tested it almost two days ago actually. Once this issue ticket was marked as resolved. Hovewer now I advise you to wait for v0.2.27 which will come out in 3-4 hours.

**Comment by jwhnat** [comment]
Okay, I didn't look.  I'll wait for the official version.  Thank you and
best regards

 Wed, Jan 18, 2023, 8:07 pm userDenis Paavilainen ***@***.***>
napisał:

**Comment by denpamusic** [comment]
It's okay. Stable version just released. It'll check that you have module B and add two additional temperature sensors `Upper buffer temp` and `Lower buffer temp`.

Don't hesitate to contact me if it doesn't work.

Thank you for using this integration and for your feedback!

**Comment by jwhnat** [comment]
I am testing v. 0.2.28.

 I noticed problems with the connection via USB-RS485.
 My converter is based on FTDI.
 It's very hard to connect, you have to try several times until you succeed.

 Upper/lower buffer temperature is working.

 There are also bugs in mixers.
 I have 2 mixers (mixer_2, mixer_3)
 Temperatures and settings and pump are missing.

 It is not stable, I think the main problem is the RS485 communication
connection

śr., 18 sty 2023, 22:30 użytkownik Denis Paavilainen <
***@***.***> napisał:

**Comment by denpamusic** [comment]
Got it. I'll see what I can do with missing frames. Easiest way wold be probably to implement some kind of request-retry mechanism due to lack of flow control in RS485.

**Comment by jwhnat** [comment]
I have now returned to version v.0.2.27, there was also a small problem with the connection, but the second time it worked.  Mixers I have mixer_1 and mixer_2 (all of them work fine).  The rest also works fine.

**Comment by denpamusic** [comment]
I've now improved protocol handler, so it should work better with RS485.
When it's convenient for you, please try to install main version as described [here](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/1#issuecomment-1334489848).
This should hopefully solve connection issues.

As for mixer numeration, it's done on purpose. Your device probably supports three mixers, but you only have last two connected.
In v0.2.27 mixer numeration was counted from 0, now it counted from 1.  So mixer_1 and mixer_2 becomes mixer_2 and mixer_3. This was done, due to some devices having mixer_0 connected, while ecoMAX manual was referring to it as mixer 1.

**Comment by denpamusic** [comment]
I've opened a new issue to keep track of stability problem with RS485: #16

**Comment by jwhnat** [comment]
Yes you are right.
 I have a master module that has one mixer (unused) and module B that has two mixers (two used)

 Ok, I'll check the "main" version and give you an answer.
 I will continue my answer in a new topic
