### ISSUE TITLE
Stability issue and missing/corrupted frames with USB to RS485 adapter

### ISSUE THREAD

**Issue by denpamusic** [denpamusic/homeassistant-plum-ecomax#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

This issue is to keep track of all problems and solutions related to using RS485 to USB adapter with this integration.

Reported by @jwhnat:
https://github.com/denpamusic/homeassistant-plum-ecomax/issues/14#issuecomment-1396902247

Multiple incorrect checksums reported by @KaRLiKCZ:
https://github.com/denpamusic/homeassistant-plum-ecomax/issues/1#issuecomment-1334533898

Related issue in PyPlumIO project:
https://github.com/denpamusic/PyPlumIO/issues/9

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

USB to RS-485 adapter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
[PyPlumIO v0.2.36](https://github.com/denpamusic/PyPlumIO/releases/tag/v0.2.36) now runs read/write operations in the same task, so it should be a lot less sensitive to timings when using direct RS485 connection.

Integration main branch was now updated to this version.
Any help with testing is greatly appreciated.

What to look out for:
  - No entities should be missing after update. (except recent mixers rename)
  - HASS log may contain at most 1-2 incorrect checksum log messages. But they should not be frequent nor periodic.
  - Connection shouldn't timeout under any circumstances.
  
  If you encounter any of the above, please write comment to this issue.
  Thank you!

**Comment by jwhnat** [comment]
I am testing the "main 660e27d" versions and there is still a problem with the connection. It takes a few tries for it to work. (connection timeout)

When trying to add an integration (Plum ecoMAX) it will sometimes connect and find only the main module, and sometimes it will connect and find the mixer as well.

Mixer parameters are disabled by default.

The parameters of the main module are correct, they work.

**Comment by denpamusic** [comment]
Try main https://github.com/denpamusic/homeassistant-plum-ecomax/commit/4def738d273d57b3b5c7a822cb3d871de33ed849. 

This one doesn't pile awaits on device add, so it shouldn't timeout.

If that still doesn't help, I'll order FTDI based device and try to recreate the issue myself.
I'll also create separate fork for you based on v0.2.27 with added buffer temps, so that you can use the integration until I resolve issue with the new protocol handler.

Thanks again for the help!

**Comment by jwhnat** [comment]
Test on "main" 641a3d3:

It's very good. Out of 6 attempts, 6 successful connections
When it connects, it sometimes detects 47 and sometimes 53 entities.

Entities get lost in mixers.

Mixer_2 works with controls and sensors (hidden pump)
There is no control in mixer_3, but sensors work (hidden pump)

The sensor readings from the main controller seem to be stable (I will check in the long run)

**Comment by denpamusic** [comment]
It's great news that stability is improved, but missing controls for only one mixer is strange🤔 EM uses single request to get parameters for all mixers so something must be not working right... Could you please send me diagnostics data to denpa@denpa.pro again? This will help to determine is problem lies with integration or pyplumio lib.

**Comment by denpamusic** [comment]
I think I figured it out.
With pump it was simply incorrect key name.
With sub-devices it was a bit more interesting, but hopefully this now fixed to. Both mixers sensors and parameters should work now.

**Comment by jwhnat** [comment]
I checked "7d63a77"

Mixers fixed, everything works.

I also noticed (not sure) that the outdoor temperature stops updating after a while. I will check it in the long run.

I have sent the diagnostic data via e-mail.

**Comment by denpamusic** [comment]
Great, then I'll wait for a while and make a release.
As for outdoor temperature, I don't think that it stops updated, I think it's just changes for less than 0.1 degree.

**Comment by jwhnat** [comment]
Yes, you are right, the external sensor was covered with snow and the temperature did not change for a long time ...

 I haven't noticed anything wrong so far.  Good job.  We are waiting for more ;)

**Comment by denpamusic** [comment]
Good job with testing too!😉

New stream handler architecture should last us a long time and make supporting new features a lot easier. Previous solution was just a bit too "hacky" and prone to breaks for my liking. It's really awesome that we managed to get new one to work.

After this release I really want to tackle thermostat (ecoSTER) support for HASS. PyPlumIO already supports both thermostat sensors and parameters and from the diagnostics that you provided I see that they are working fine.

In the meantime if you need some other sensor added, feel free to scan your diagnostic data and open an issue, if you find something that might be useful.
