### ISSUE TITLE
Incorrect values are being sent to the ecoSTER panel

### ISSUE THREAD

**Issue by denpamusic** [denpamusic/homeassistant-plum-ecomax#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Initially reported in #19 by @tusiek5.

I am testing the thermostat, the display of the current temperature seems to work correctly, but errors occur when setting a new value. After selecting a new temperature in HA, it is displayed correctly, while on ecoSter (room panel) a strange value appears, for example 199. Other times everything is fine; so far I do not see any diagram what could cause this error. I attach the diagnostics, the set temperature in HA 22.5, the room panel (ecoster) displays 48.1.

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [X] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### My diagnostics data:

[config_entry-plum_ecomax-03ce1ae2c806291cb6b21cc566e32df0.json.7.txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/10668342/config_entry-plum_ecomax-03ce1ae2c806291cb6b21cc566e32df0.json.7.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Byte length of the value previously wasn't taken into account which resulted in the incomplete frame being sent.
It should now be fixed in: https://github.com/denpamusic/PyPlumIO/commit/61b20afc52cb82182897b927e08cc3bfe9ebf2f4

**Comment by tusiek5** [comment]
Setting the new temperature works correctly, for more than 20 switchings all settings were correct and no error appeared.
Thanks for the quick response, you're doing a really good job.
Regards

**Comment by denpamusic** [comment]
Awesome! Glad that in works fine.
Thank you very much for the testing!
I wouldn't have done it without you, since I don't have ecoSTER myself.
I'll release beta 2 then, then we'll wait for a couple days, just to make sure, that no more issues creep up and do the final 0.3.4.
