### ISSUE TITLE
Ash pan sensor

### ISSUE THREAD

**Issue by denpamusic** [denpamusic/homeassistant-plum-ecomax#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [ ] support for a new product
- [X] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

Initially requested in #19 by @tusiek5.

I have identified the parameter responsible for filling the ashtray ("227": 55).

<details>
<summary>ecoMAX 860P3-O regdata:</summary>

```
"1792": 3,
"1538": false,
"1536": true,
"1539": false,
"1": false,
"1541": true,
"1542": false,
"2": false,
"3": false,
"4": false,
"1544": true,
"1545": false,
"1546": false,
"5": false,
"222": false,
"1547": false,
"1548": false,
"1549": false,
"1550": false,
"1551": false,
"1552": false,
"6": false,
"223": false,
"1553": false,
"1554": false,
"1555": false,
"1556": false,
"1557": false,
"1558": false,
"7": false,
"14": 2348,
"11": 1279,
"10": 2534,
"9": 1977,
"15": 4095,
"13": 2109,
"8": 1712,
"16": 214,
"12": 2561,
"17": 182,
"18": 0,
"19": 0,
"20": 0,
"21": 0,
"22": 0,
"23": 0,
"24": 0,
"25": 0,
"26": 0,
"27": 0,
"28": 0,
"29": 0,
"1024": 58.2193603515625,
"1026": 24.595382690429688,
"1027": 1.8267631530761719,
"1025": 45.94587707519531,
"32": NaN,
"31": 49.66331481933594,
"1031": 37.54756164550781,
"33": NaN,
"30": 36.46145248413086,
"34": NaN,
"1028": NaN,
"1033": NaN,
"1032": NaN,
"1029": NaN,
"35": NaN,
"36": NaN,
"37": NaN,
"1035": NaN,
"1034": NaN,
"38": NaN,
"39": NaN,
"40": NaN,
"1280": 63,
"1282": 0,
"1283": 0,
"1281": 45,
"43": 0,
"42": 0,
"1287": 39,
"44": 0,
"41": 0,
"45": 0,
"1284": 0,
"1289": 36,
"1288": 36,
"1285": 0,
"46": 0,
"47": 0,
"48": 0,
"1291": 36,
"1290": 36,
"49": 0,
"50": 0,
"51": 0,
"58": 0,
"55": 0,
"54": 0,
"53": 0,
"59": 0,
"57": 0,
"52": 0,
"60": 0,
"56": 0,
"61": 0,
"62": 0,
"63": 8,
"64": 8,
"65": 0,
"66": 0,
"67": 0,
"70": 0,
"68": 8,
"69": 8,
"71": 0,
"72": 0,
"73": 0,
"80": false,
"77": false,
"76": false,
"75": false,
"81": true,
"79": false,
"74": false,
"82": true,
"78": false,
"83": true,
"84": true,
"85": true,
"86": true,
"87": true,
"88": true,
"89": true,
"90": true,
"91": true,
"92": true,
"93": true,
"94": true,
"95": true,
"96": false,
"109": 0,
"97": false,
"98": false,
"99": false,
"100": false,
"101": false,
"102": false,
"103": false,
"104": false,
"105": false,
"106": false,
"107": false,
"108": false,
"110": 8,
"111": false,
"112": false,
"2049": 0,
"113": false,
"114": false,
"115": false,
"116": false,
"117": false,
"118": false,
"119": false,
"120": false,
"121": false,
"122": false,
"123": false,
"126": false,
"125": false,
"124": false,
"127": false,
"128": false,
"129": false,
"130": false,
"131": false,
"132": false,
"133": false,
"2048": 2,
"134": false,
"135": false,
"136": true,
"137": false,
"138": false,
"139": false,
"140": true,
"145": 1.752262830734253,
"146": 0,
"206": false,
"207": false,
"208": true,
"209": false,
"210": false,
"211": false,
"212": true,
"204": 3.109999895095825,
"205": 17.889999389648438,
"142": false,
"1798": true,
"143": true,
"144": false,
"1543": false,
"1540": false,
"224": false,
"1794": 50,
"1793": 8.989108085632324,
"147": true,
"148": true,
"149": false,
"150": false,
"151": false,
"152": false,
"153": 14,
"154": 80,
"155": 1,
"156": 23,
"157": 0,
"158": 0,
"159": 0,
"160": 0,
"161": 0,
"162": 0,
"163": 0,
"164": 0,
"165": 0,
"166": false,
"167": false,
"168": false,
"169": false,
"170": false,
"171": 0,
"172": 0,
"173": 0.0,
"174": 0.0,
"213": 22.250240325927734,
"216": 22.5,
"219": 2,
"214": 0.0,
"217": 0.0,
"220": 255,
"215": 0.0,
"218": 0.0,
"221": 255,
"1795": 73,
"176": 0.0,
"178": 0,
"179": 0,
"180": NaN,
"181": 8.069148063659668,
"182": 600,
"183": 4462,
"184": 2053,
"185": 352,
"186": 2181,
"187": 22905.93359375,
"188": 10874,
"189": 176,
"190": 4083,
"191": "192.168.0.54",
"192": "255.255.255.0",
"193": "0.0.0.0",
"194": 1,
"195": "0.0.0.0",
"196": "255.255.255.0",
"197": "0.0.0.0",
"198": 1,
"199": 1,
"200": 100,
"201": 0,
"202": 0,
"203": "",
"225": NaN,
"226": 5.1027116775512695,
"227": 49,
"228": 691200000
```
</details>

### My diagnostics data:

[config_entry-plum_ecomax-03ce1ae2c806291cb6b21cc566e32df0.json.1.txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/10668667/config_entry-plum_ecomax-03ce1ae2c806291cb6b21cc566e32df0.json.1.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
This is contained in regdata message and is device-specific.
Will be added in next version, specifically for `product_type=0` and `product_id=51`, which is ecoMAX 860P3-O.

**Comment by denpamusic** [comment]
@Gtis69
Thank you for the diagnostics!

This confirms my earlier suspicion, that same models CAN in fact have different ids.

If possible, please wait until v0.4.2 release that will include this feature: https://github.com/denpamusic/homeassistant-plum-ecomax/issues/58

With this you will be able to add the sensor by yourself.

Sadly, currently there's no ETA on the release, since I've been busy with other stuff this winter. Hopefully I'll be able to work more on this project next weekend.

**Comment by jszkiela72** [comment]
Does version 0.4.2 allow the creation of new entities? I wanted to add ash pan filling for ecoMAX 860P6-O (identified regdata 223) but I don't know how to do it.

Regards, Jarek

**Comment by denpamusic** [comment]
@jszkiela72 
> Does version 0.4.2 allow the creation of new entities?

Not yet, this feature can be tracked [here](https://github.com/denpamusic/homeassistant-plum-ecomax/pull/76) and is currently scheduled for next major v0.5.x. v0.4.2 is almost purely bugfix release.

I can add it for you manually for now, as it doesn't seem to collide with any other model, so you can use it on main branch right away, but you'll need to recreate it yourself once v0.5.x comes out.

**Comment by denpamusic** [comment]
@jszkiela72 
> If you can, you add manually to main.
> 
> Regards, Jarek

Done.
The sensor will be available, once you install [main](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/35).

For other users, please note, that this will be last time the regdata sensor is added via this mechanism. Please consider this part of codebase frozen until release of v0.5.x, which will bring about a new mechanism, that'll allow users to add their own sensors.
