### ISSUE TITLE
Can't connect to the device, retrying in 20.0 seconds

### ISSUE THREAD

**Issue by OvidiuPreda** [denpamusic/homeassistant-plum-ecomax#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

I'm able to establish serial connection and retrieve values from Ecomax using a python file I created for testing purposes but in Home Assistant I get the a 
 "Can't connect to the device, retrying in 20.0 seconds" error every time I try to configure the Plum EcoMAX integration. Is there any way to fix this or at least provide guidance on how to troubleshoot the issue?
![Screenshot_2023-02-15-14-31-42-735_com android chrome](https://user-images.githubusercontent.com/3982433/219029873-a580b067-95a3-4ad5-8ca4-7be4cd60f9bb.jpg)

**My Python code that is working and print the heating_temp value from EcoMAX** "

`import asyncio
import pyplumio
import logging

_LOGGER = logging.getLogger(__name__)

async def main():
  async with pyplumio.open_serial_connection("/dev/ttyUSB0", baudrate=115200) as connection:
    # You can also use optional timeout parameter of get method.
    try:
      ecomax = await connection.get("ecomax", timeout=30)
      print ("Temperatura apa")
      print(await ecomax.get("heating_temp"))
    except asyncio.TimeoutError:
      _LOGGER.error("Failed to get device within 10 seconds")
	
asyncio.run(main())`

### My environment is:

```markdown
- OS: Raspbian GNU/Linux 11 (bullseye)"
- Python: 3.10
```

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

USB to RS-485 adapter

### I'm seeing following log messages:

```shell
Logger: pyplumio.connection
Source: .local/lib/python3.10/site-packages/pyplumio/connection.py:97
First occurred: 14:23:29 (4 occurrences)
Last logged: 14:24:29
Can't connect to the device, retrying in 20.0 seconds
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Moved the issue to the integration repo, since the issue is happening with the integration.

**Comment by denpamusic** [comment]
Thank you very much for the heads up! I'm glad that you've got it working!👍 I'll add this information to the readme just in case.
