### ISSUE TITLE
Make baudrate configurable

### ISSUE THREAD

**Issue by stskrp** [denpamusic/homeassistant-plum-ecomax#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [ ] support for a new product
- [x] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

Hello,

I have old ecoMAX800 and it seems that it has baudrate 19200 (I'm able to get values using custom esphome code with such baudrate, but not able to make any switches). Frame format seems to be same.
Would it be possible to make serial port baudrate configurable so that I could try this component with other baudrate?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!👍

Great idea! PyPlumIO already supports this feature, so it won't be too hard to implement in the integration.
I'll add this feature for the next version.

**Comment by denpamusic** [comment]
Thanks for waiting! This is now done. You can install **main** branch through hacs as described [here](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/1#issuecomment-1334489848) to test it right away or wait for a stable release, which will happen somewhere around of 2023.3 release of the Home Asssistant.

If you encounter any other problems don't hesitate to open a new issue. Recently, we've been striving to achieve strictly one problem per issue to make searching though them easier for the new users.
