### ISSUE TITLE
Add Mixer settings 

### ISSUE THREAD

**Issue by jwhnat** [denpamusic/homeassistant-plum-ecomax#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [ ] support for a new product
- [X] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

Is it possible to add settings to mixers?

Mixer settings:
* Disabled
* Switchable CO
* Enabled floor
* Pump only

I have 2 mixers (ground floor, first floor) and I cannot turn it on remotely.

### My diagnostics data:

[config_entry-plum_ecomax-8b2b653e598db0f5ad9e34db23aca49e.json.txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/11230301/config_entry-plum_ecomax-8b2b653e598db0f5ad9e34db23aca49e.json.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi, thank you very much for for the feedback!

I found reference to this setting in the diagnostics that you provided (really appreciated btw!👍) and manual for you device, so I can easily add this.

![Screenshot 2023-04-14 at 12-28-49 burner-controller-ecomax-850p2-c-touch-manual](https://user-images.githubusercontent.com/16575433/232007545-b5f3eced-378d-445f-9aff-999a5904a529.png)

```python
MixerParameter(
    device=Mixer,
    description=MixerParameterDescription(
        name='work_mode',
        cls=<class 'pyplumio.structures.mixer_parameters.MixerParameter'>,
        multiplier=1,
        offset=0
    ),
   value=0.0,
   min_value=0.0,
   max_value=3.0
)
```

Selector values:
- 0 - Off
- 1 - CH on
- 2 - Floor on
- 3 - Pump only

If it's okay with you, this parameter will be added in the next version as a device-specific selector _for your ecoMAX model only_, since we currently can't be sure, that selector values will stay the same across all EM-p devices.

**Comment by denpamusic** [comment]
This is now done.

The aforementioned commit adds support for a `Work mode` selector for mixer/circuit devices. You can either install main branch as described [here](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/1#issuecomment-1334489848) and try it right away or wait for a stable release, which is set to come out on April, 16th. 

After careful consideration and research I decided to make `Work mode` select available for all ecoMAX-p controllers. As far as I can see, currently we can expect work modes to be the same for all existing models. If that changes in the future, then will use a product_id filter.

Thanks again for the feedback and feel free to contact me, it you have any other questions.

**Comment by jwhnat** [comment]
Hi mate you are doing a good job.

Only now I uploaded v.0.3.7 and noticed a problem with mixer 2.
No sensor status.
The select button does nothing.

Mixer 3 works ok.

It's possible that it's an addressing problem with module B

**Comment by jwhnat** [comment]
![Firefox_Screenshot_2023-04-16T17-08-37 575Z](https://user-images.githubusercontent.com/121961851/232328607-e1c97ce0-e1ce-4ffb-b062-41949160e1c8.png)

**Comment by denpamusic** [comment]
For missing sensors, did you try to reload integration? This should probably fix it, since there was no changes related to mixer sensors in this version, that could cause such behaviour.

As for not working selector, that is strange. Could you please send me diagnostic data once more.

**Comment by jwhnat** [comment]
No, I spelled it wrong.
The button works on both mixers, but on mixer 2 it has no effect. no

Mixer 2 didn't work before, but I didn't have time to write about it. I thought the problem would go away with the update.

Diagnostics with: mixer 3 - floor on, mixer 2 - off

**Comment by jwhnat** [comment]
[config_entry-plum_ecomax-3cf93b62395a68d12f347dea266765f7.json.txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/11243115/config_entry-plum_ecomax-3cf93b62395a68d12f347dea266765f7.json.txt)

**Comment by denpamusic** [comment]
Thank you for the help!
I can now confirm, that at least I identified parameter properly and problem lies elsewhere.

> Mixer 2 didn't work before, but I didn't have time to write about it. I thought the problem would go away with the update.

I see. I'll look into it further then. There is only one place that could've resulted in the problem like this, since in diagnostics data, that you provided both mixers are correctly represented. Hopefully I can quickly locate and fix it.

**Comment by denpamusic** [comment]
I rechecked MixerEntity class, and everything should work with you setup.
Did you try to activate sensors of mixer 2 manually.
If they were not detected on first setup, the integration won't try to add them later.

1. To manually activate entity, click on it's name, then click gear icon in top right corner of modal window:

![2023-04-16](https://user-images.githubusercontent.com/16575433/232339326-a3798ca1-b246-4cf9-b3e6-ee32f7ed1f5a.png)

3. Click `Advanced settings`, then in `Entity status` section select `Enabled`:

![2023-04-16 (1)](https://user-images.githubusercontent.com/16575433/232339415-145b0cf4-4ec2-409c-82b1-d50ee198702b.png)

Sensors should start working within 30 seconds or so.

**Comment by jwhnat** [comment]
Yes you are right.  You had to add sensors manually.  Probably because at the time of updating to 0.3.7 mixer was turned off and didn't download data.

 Now everything works.

**Comment by denpamusic** [comment]
Thanks for the heads up!
Glad that you've managed to make it work.
Closing this for now then, feel free to reopen if problem arises again.
