### ISSUE TITLE
Get parameter service

### ISSUE THREAD

**Issue by niq83** [denpamusic/homeassistant-plum-ecomax#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Hello,

In HASS services the "get parameter" does not show up.

I  am using latest version of HASS

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [ ] ecoMAX 8xx series
- [X] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

USB to RS-485 adapter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Since you didn't provide diagnostics, I must ask you just in case, did you update this integration to v0.3.11 and restarted HASS?

**Comment by niq83** [comment]
It worked after reboot. Restarting HASS din not provide the new services.

Thank You !

În sâm., 7 oct. 2023 la 11:31, Denis Paavilainen ***@***.***>
a scris:

**Comment by denpamusic** [comment]
Thanks for the heads up! That's strange... HASS restart should've really been enough, but I'm glad that a least you've got it working in the end.
