### ISSUE TITLE
When change room thermostat set temperature, not changed setting in HA 

### ISSUE THREAD

**Issue by Safs** [denpamusic/homeassistant-plum-ecomax#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

When change room thermostat set temperature (ecoSTER), not changed thermostat value in HA.

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [X] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [X] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### My diagnostics data:

[config_entry-plum_ecomax-e0b403046d4ad77e983a2eb9b33db3b7.json (2).txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/12837125/config_entry-plum_ecomax-e0b403046d4ad77e983a2eb9b33db3b7.json.2.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thanks for the feedback!

Does this only happen when running in schedule mode, or any other mode as well?

**Comment by Safs** [comment]
When change mode, then HA thermostat get right value, same as set for respectiv mode. But if I change temp for that mode after that, then HA thermostat not changing. That is in any mode (away, party, etc)

**Comment by Safs** [comment]
So, if I change set tempereture on room thermostat, HA termostat value not changing  in any mode.

**Comment by denpamusic** [comment]
Understood. Thank you!
I'll look into it a bit later today.

**Comment by denpamusic** [comment]
I think I've got it.

It seems that changing temperature on ecoSTER itself, doesn't necessary update related "day_target_temp" and "night_target_temp" parameters, only changing "target_temp" sensor.
This can either be caused by an error when PyPlumIO library doesn't get notified that there's changes in thermostat, which is unlikely since from your diagnostics I see that version number for frame_id=92 is steadily increasing, or by really weird design decision on Plum's part.

To fix this, I've decided to pull target temperature value for thermostat from "target_temp" sensor instead of aforementioned parameters.

Could you please test by [installing main branch](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/35).
 Thanks beforehand.

**Comment by Safs** [comment]
Now it is working well except if I select "Airing", then mode not changing in HA thermostat. In this mode not changing temperature, but only switching off mixer pump. 
There is diagnostic data:
[config_entry-plum_ecomax-e0b403046d4ad77e983a2eb9b33db3b7.json (3).txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/12839976/config_entry-plum_ecomax-e0b403046d4ad77e983a2eb9b33db3b7.json.3.txt)

**Comment by Safs** [comment]
And same, when EcoSter change mode by it self from Airing to previous mode, in HA thermostat mode is not changing.
[config_entry-plum_ecomax-e0b403046d4ad77e983a2eb9b33db3b7.json (4).txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/12840094/config_entry-plum_ecomax-e0b403046d4ad77e983a2eb9b33db3b7.json.4.txt)

**Comment by denpamusic** [comment]
Thanks for diagnostics and testing!

There's another design quirk is seems.
`state` sensor doesn't change number when in airing mode. In all other modes, except for airing (4), is assumes current mode number 0-7.
Now we subscribe to "mode" parameter instead, and it seem to work as expected.
Hopefully this fixes the issue with airing mode.

When you have time, could you please retest. Thank you!

**Comment by Safs** [comment]
Now airing mode work, but not other mode changings.
In file is set eco mode in ecoster, but in HA thermostat mode is still "schedule"

[config_entry-plum_ecomax-e0b403046d4ad77e983a2eb9b33db3b7.json (5).txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/12840275/config_entry-plum_ecomax-e0b403046d4ad77e983a2eb9b33db3b7.json.5.txt)

**Comment by denpamusic** [comment]
OK. This gets complicated. Then I guess we'll need to subscribe to both `mode` for airing and `state` for other modes.

**Comment by denpamusic** [comment]
Done.
Now we only listen to parameter update for airing mode, other modes we pull from `state` sensor.
This should make all modes work.

**Comment by Safs** [comment]
Switching to airing mode is working, but switching back is not.
As I see, same situation with all modes, where is possible to set mode working time - airing, away, holiday, party, HUW force. 
[config_entry-plum_ecomax-e0b403046d4ad77e983a2eb9b33db3b7.json (6).txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/12840451/config_entry-plum_ecomax-e0b403046d4ad77e983a2eb9b33db3b7.json.6.txt)

**Comment by denpamusic** [comment]
I think we've at least getting there.
I'm really sorry for all the trouble.
Could you please update and try again.
If it still not working right, I'll buy an ecoSTER and try to reverse-engineer it myself.

**Comment by Safs** [comment]
No problem, big thanks for all that job what are you done for this integration!
Now seem to all working well! Thanks again!
If you need any info about EcoSTER in future, you can ask to me!

**Comment by denpamusic** [comment]
> Thanks again!

You're very welcome! Thanks for all you great help with testing!
Glad that we managed to fix it in the end.
I'll keep this issue open until v0.3.13 release, just in case something else pops up.
