### ISSUE TITLE
"Invalid handler specified" error

### ISSUE THREAD

**Issue by jerguitariste** [denpamusic/homeassistant-plum-ecomax#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Ajouter un pont 
![image](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/91892609/66bc60df-1892-4664-aca2-de436e561e60)
pareil si je veux déinstaller

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

```shell
Ajouter un pont 
![image](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/91892609/66bc60df-1892-4664-aca2-de436e561e60)
pareil si je veux déinstaller
```

### My diagnostics data:

Ajouter un pont 
![image](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/91892609/66bc60df-1892-4664-aca2-de436e561e60)
pareil si je veux déinstaller

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!

Please provide log from HASS after this message appears, otherwise I sadly cannot help you. Thanks beforehand!

**Comment by jerguitariste** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:863
First occurred: 12 octobre 2023 à 20:29:13 (2 occurrences)
Last logged: 10:58:19

Error occurred loading flow for integration plum_ecomax: cannot import name 'ServiceResponse' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
