### ISSUE TITLE
[ecoMAX 860P6-O] Add opening value (%) for SM A - mixing valve - circuit A.

### ISSUE THREAD

**Issue by denpamusic** [denpamusic/homeassistant-plum-ecomax#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [ ] support for a new product
- [X] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

Initially asked by @jszkiela72 here: https://github.com/denpamusic/PyPlumIO/issues/19#issuecomment-1852835453

> 2. Can the integration read the opening value (%) for SM A - mixing valve -
circuit A from the controller?

### My diagnostics data:

[config_entry-plum_ecomax-3d173fc70d439aca63ce86c959ccc479.json.txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/13653823/config_entry-plum_ecomax-3d173fc70d439aca63ce86c959ccc479.json.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Yes, it is probably can.
Though this is likely a device specific (regdata) sensor, much like [this one](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/46), so you'll need to do a bit of research with the diagnostics data for your device.

1. Note the current value on the controller.
2. Download [diagnostics](https://www.home-assistant.io/integrations/diagnostics/) from HomeAssistant and open it with your favorite text editor.
3. Search for "regdata" key. It should look like the one below.
4. Try to locate which key corresponds to the value that you want added and comment it under this issue.
<details>
  <summary>ecoMAX 860P6-O regdata</summary>

```json
"regdata": {
  "1792": 4,
  "1538": true,
  "1536": true,
  "1539": true,
  "1": false,
  "1541": true,
  "1542": true,
  "2": false,
  "3": false,
  "4": false,
  "1544": true,
  "1545": false,
  "1546": false,
  "5": false,
  "218": false,
  "1547": false,
  "1548": false,
  "1549": false,
  "1550": false,
  "1551": false,
  "1552": false,
  "6": false,
  "219": false,
  "1553": false,
  "1554": false,
  "1555": false,
  "1556": false,
  "1557": false,
  "1558": false,
  "7": false,
  "14": 1231,
  "11": 2256,
  "10": 2984,
  "9": 1596,
  "15": 209,
  "13": 4094,
  "8": 1757,
  "16": 2,
  "12": 189,
  "17": 1,
  "18": 0,
  "19": 0,
  "20": 0,
  "21": 0,
  "22": 0,
  "23": 0,
  "24": 0,
  "25": 0,
  "26": 0,
  "27": 0,
  "28": 0,
  "29": 0,
  "1024": 45.37066650390625,
  "1026": 20.317138671875,
  "1027": 3.75579833984375,
  "1025": 35.490020751953125,
  "32": -16.73095703125,
  "31": NaN,
  "1031": 31.550079345703125,
  "33": NaN,
  "30": 99.44315338134766,
  "34": NaN,
  "1028": NaN,
  "1033": NaN,
  "1032": NaN,
  "1029": NaN,
  "35": NaN,
  "36": NaN,
  "37": NaN,
  "1035": NaN,
  "1034": NaN,
  "38": NaN,
  "39": NaN,
  "40": NaN,
  "1280": 60,
  "1281": 40,
  "1287": 35,
  "1288": 35,
  "1289": 35,
  "1290": 35,
  "1291": 35,
  "58": 1,
  "53": 0,
  "52": 8,
  "64": 8,
  "63": 8,
  "69": 8,
  "68": 8,
  "74": 8387232,
  "87": 0,
  "75": false,
  "76": false,
  "77": false,
  "78": false,
  "79": false,
  "80": false,
  "81": false,
  "82": false,
  "83": false,
  "84": false,
  "85": false,
  "86": false,
  "88": 195,
  "89": false,
  "90": false,
  "2049": 0,
  "91": false,
  "92": false,
  "93": false,
  "94": false,
  "95": false,
  "96": false,
  "97": false,
  "98": false,
  "99": false,
  "100": false,
  "101": false,
  "104": false,
  "103": false,
  "102": false,
  "105": false,
  "106": false,
  "107": false,
  "108": false,
  "109": false,
  "110": false,
  "111": false,
  "2048": 2,
  "112": false,
  "113": false,
  "114": true,
  "115": false,
  "116": false,
  "117": false,
  "118": true,
  "123": 4.902099609375,
  "124": 0,
  "187": false,
  "188": false,
  "189": true,
  "190": false,
  "191": false,
  "192": false,
  "193": true,
  "184": 10.430000305175781,
  "185": 9.569999694824219,
  "120": false,
  "1798": true,
  "121": true,
  "122": false,
  "1543": false,
  "1540": false,
  "220": false,
  "1794": 100,
  "1793": 23.383014678955078,
  "125": true,
  "126": true,
  "127": false,
  "128": false,
  "129": false,
  "130": false,
  "131": 17,
  "132": 80,
  "133": 1,
  "134": 71,
  "135": 0,
  "136": 0,
  "137": 0,
  "138": 0,
  "139": 0,
  "140": 0,
  "141": 0,
  "142": 0,
  "143": 0,
  "144": false,
  "145": false,
  "146": false,
  "147": false,
  "148": false,
  "149": 0,
  "150": 0,
  "151": 0.0,
  "152": 0.0,
  "194": 19.12551498413086,
  "197": 20.0,
  "200": 0,
  "203": 0,
  "206": 0,
  "209": 0,
  "212": 0,
  "215": 0,
  "195": 0.0,
  "198": 0.0,
  "201": 127,
  "204": 0,
  "207": 0,
  "210": 0,
  "213": 0,
  "216": 0,
  "196": 0.0,
  "199": 0.0,
  "202": 127,
  "205": 0,
  "208": 0,
  "211": 0,
  "214": 0,
  "217": 0,
  "1795": 36,
  "154": 0.0,
  "156": 0,
  "157": 0,
  "158": 8.100000381469727,
  "159": 8.020307540893555,
  "160": 342,
  "161": 70,
  "162": 0,
  "163": 0,
  "164": 35,
  "165": 329.4720764160156,
  "166": 27,
  "167": 6,
  "168": 33,
  "169": 0,
  "170": 0,
  "186": 0,
  "171": "192.168.100.124",
  "172": "255.255.255.0",
  "173": "0.0.0.0",
  "174": 1,
  "175": "0.0.0.0",
  "176": "255.255.255.0",
  "177": "0.0.0.0",
  "178": 1,
  "179": 1,
  "180": 100,
  "181": 0,
  "182": 0,
  "183": "",
  "221": NaN,
  "222": 236.29254150390625,
  "223": 21,
  "224": 0
}
```
</details>

**Comment by jszkiela72** [comment]
"regdata": {
        "1792": 4,
        "1538": false,
        "1536": true,
        "1539": false,
        "1": false,
        "1541": true,
        "1542": false,
        "2": false,
        "3": false,
        "4": false,
        "1544": true,
        "1545": false,
        "1546": false,
        "5": false,
        "218": false,
        "1547": false,
        "1548": false,
        "1549": false,
        "1550": false,
        "1551": false,
        "1552": false,
        "6": false,
        "219": false,
        "1553": false,
        "1554": false,
        "1555": false,
        "1556": false,
        "1557": false,
        "1558": false,
        "7": false,
        "14": 838,
        "11": 1942,
        "10": 2858,
        "9": 1453,
        "15": 189,
        "13": 1248,
        "8": 1401,
        "16": 4094,
        "12": 58,
        "17": 1,
        "18": 0,
        "19": 0,
        "20": 0,
        "21": 0,
        "22": 0,
        "23": 0,
        "24": 0,
        "25": 0,
        "26": 0,
        "27": 0,
        "28": 0,
        "29": 0,
        "1024": 58.9879150390625,
        "1026": 27.314453125,
        "1027": 6.82568359375,
        "1025": 39.15118408203125,
        "32": -16.83349609375,
        "31": 44.8519287109375,
        "1031": 40.547088623046875,
        "33": NaN,
        "30": 99.99998474121094,
        "34": NaN,
        "1028": NaN,
        "1033": NaN,
        "1032": NaN,
        "1029": NaN,
        "35": NaN,
        "36": NaN,
        "37": NaN,
        "1035": NaN,
        "1034": NaN,
        "38": NaN,
        "39": NaN,
        "40": NaN,
        "1280": 60,
        "1281": 40,
        "1287": 40,
        "1288": 32,
        "1289": 32,
        "1290": 32,
        "1291": 32,
        "58": 16,
        "53": 0,
        "52": 8,
        "64": 8,
        "63": 8,
        "69": 8,
        "68": 8,
        "74": 8387200,
        "87": 0,
        "75": false,
        "76": false,
        "77": false,
        "78": false,
        "79": false,
        "80": false,
        "81": false,
        "82": false,
        "83": false,
        "84": false,
        "85": false,
        "86": false,
        "88": 140,
        "89": false,
        "90": false,
        "2049": 0,
        "91": false,
        "92": false,
        "93": false,
        "94": false,
        "95": false,
        "96": false,
        "97": false,
        "98": false,
        "99": false,
        "100": false,
        "101": false,
        "104": false,
        "103": false,
        "102": false,
        "105": false,
        "106": false,
        "107": false,
        "108": false,
        "109": false,
        "110": false,
        "111": false,
        "2048": 2,
        "112": false,
        "113": false,
        "114": true,
        "115": false,
        "116": false,
        "117": false,
        "118": true,
        "123": 2.946373224258423,
        "124": 0,
        "187": false,
        "188": false,
        "189": true,
        "190": false,
        "191": false,
        "192": false,
        "193": true,
        "184": 6.010000228881836,
        "185": 13.979999542236328,
        "120": false,
        "1798": true,
        "121": true,
        "122": false,
        "1543": false,
        "1540": false,
        "220": false,
        "1794": 61,
        "1793": 14.054200172424316,
        "125": true,
        "126": true,
        "127": false,
        "128": false,
        "129": false,
        "130": false,
        "131": 17,
        "132": 80,
        "133": 1,
        "134": 35, # Mixer valve, (Polish: Otwarcie zaworu mieszacza).
        "135": 0,
        "136": 0,
        "137": 0,
        "138": 0,
        "139": 0,
        "140": 0,
        "141": 0,
        "142": 0,
        "143": 0,
        "144": false,
        "145": false,
        "146": false,
        "147": false,
        "148": false,
        "149": 0,
        "150": 0,
        "151": 0.0,
        "152": 0.0,
        "194": 18.999942779541016,
        "197": 21.5,
        "200": 0,
        "203": 0,
        "206": 0,
        "209": 0,
        "212": 0,
        "215": 0,
        "195": 0.0,
        "198": 0.0,
        "201": 127,
        "204": 0,
        "207": 0,
        "210": 0,
        "213": 0,
        "216": 0,
        "196": 0.0,
        "199": 0.0,
        "202": 127,
        "205": 0,
        "208": 0,
        "211": 0,
        "214": 0,
        "217": 0,
        "1795": 30,
        "154": 0.0,
        "156": 0,
        "157": 0,
        "158": 8.100000381469727,
        "159": 8.003862380981445,
        "160": 136,
        "161": 136,
        "162": 4,
        "163": 0,
        "164": 69,
        "165": 645.2617797851562,
        "166": 57,
        "167": 6,
        "168": 37,
        "169": 0,
        "170": 0,
        "186": 0,
        "171": "192.168.100.124",
        "172": "255.255.255.0",
        "173": "0.0.0.0",
        "174": 1,
        "175": "0.0.0.0",
        "176": "255.255.255.0",
        "177": "0.0.0.0",
        "178": 1,
        "179": 1,
        "180": 100,
        "181": 0,
        "182": 0,
        "183": "",
        "221": NaN,
        "222": 218.5303497314453,
        "223": 27,
        "224": 0
      },
      "frame_errors": [
        61
      ],
      "loaded": true
    }
  }
}

**Comment by denpamusic** [comment]
Thank you for the research and translation! I will add it ASAP.

**Comment by jszkiela72** [comment]
By the way, can you also add the valve status?

"139": 0 - Not running, 1 - Closing, 2 - Opening (Polish: Stan zaworu,  0 - Nie działa, 1 - Zamykanie, 2 - Otwieranie)

**Comment by denpamusic** [comment]
Thanks for waiting!

This has now been added as device-specific regdata sensor in this commit: https://github.com/denpamusic/homeassistant-plum-ecomax/commit/eccb9802711a0f3064a67980aa614f79cf437466

You can now wait for a stable release or test it right now by [installing the main branch](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/35)!

> By the way, can you also add the valve status?
> "139": 0 - Not running, 1 - Closing, 2 - Opening (Polish: Stan zaworu, 0 - Nie działa, 1 - Zamykanie, 2 - Otwieranie)

OK, I'll add this next. Thanks!

**Comment by jszkiela72** [comment]
Hi
I installed the main version. I know that there are entities related to the mixer valve. They are visible in the ecoMAX 860P6-O device. I think they concern ecoMAX 860P6-O Mixer 1 and should be visible there. What do you think about this?

**Comment by denpamusic** [comment]
Hi,

I think you're right, but sadly it's not possible to add regdata entities to a sub-device with current RegData entity class implementation. I could change it of course, but I think there's enough potentialy breaking changes for v0.4.1, I'm already scared to release it as is :)

If it's alright with you, I'll consider it as a feature request for the next minor v0.4.2.

**Comment by jszkiela72** [comment]
It's nothing important.  You did a great job.  Thank you very much.

Regards Jarek

czw., 14 gru 2023, 22:36 użytkownik Denis Paavilainen <
***@***.***> napisał:
