### ISSUE TITLE
Cannot connect to ecoMAX850P-ZT (econet300) via network

### ISSUE THREAD

**Issue by AlexSyxar** [denpamusic/homeassistant-plum-ecomax#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

I'm not sure if it is a bug, or just i am doing something wrong

I'm trying to add integration, but getting an error
![econet](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/157969427/4d3b8e00-589b-464f-94fe-acf4383c622f)
What port is being used to connect? Default 8899 is not working

ID: ecoMAX850P-ZT 
FW veriosns:
 Module ecoNET version: 3.2.3819
Module A version:1.12.9
Module Panel version:1.30.5

Many thanks in advance!

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [X] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

```shell
Timeout establishing connection
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!

This integration is not designed to work with ecoNET300 device from Plum. It is designed to work with either RS485 to USB adapters, like [this one](https://www.amazon.com/Industrial-USB-RS485-Converter-Communication/dp/B081MB6PN2/ref=mp_s_a_1_1?keywords=usb+to+rs485+adapter&qid=1706456470&sr=8-1) or RS485 to WiFi converters, like [this one](https://www.amazon.com/Smallest-Elfin-EW11-Elfin-EW11-0-Wireless-Networking/dp/B0833XTK92/ref=mp_s_a_1_1?crid=2GNF0JYKTGPEY&keywords=elfin+ew11a&qid=1706456561&sprefix=elfin+ew%2Caps%2C463&sr=8-1).

If you want to use ecoNET300, please use ecoNET300 integration by @jontofront: https://github.com/jontofront/ecoNET-300-Home-Assistant-Integration
