### ISSUE TITLE
Cannot connect to ecoMAX810

### ISSUE THREAD

**Issue by sundeveu** [denpamusic/homeassistant-plum-ecomax#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Hardware:
- HP T620 (IP: 192.168.10.61)
- Elfin-EW11 (IP: 192.168.10.65)
- Sonoff ZBDongle-P

HA installed as Home Assistant Operating System:
- Core 2024.2.1
- Supervisor 2024.01.1
- Operating System 11.5
- User Interface 20240207.1
- Installed: HACS, MQTT

Plum equipment:
- ecoMax810 P3 + ecoMax800 panel

Tried all possible EW11 settings for RS485 and network and all the time trying add Plum integration  (TCP 192.168.10.65:8899)  finishing with message "No Plum devices found". I don't know what is the problem HA can't connect to EW11 or EW11 can't connect to Plum or something else... From HA terminal add-on I can ping EW11.

Connection looks like:
![connection](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/115409412/ad0072d0-eef4-4ef2-8eb0-e603eeeed42b)

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

```shell
Logger: pyplumio.connection
Source: runner.py:188
First occurred: 21:04:26 (1 occurrences)
Last logged: 21:04:26
Can't connect to the device, retrying in 20.0 seconds

Logger: custom_components.plum_ecomax.config_flow
Source: custom_components/plum_ecomax/config_flow.py:189
Integration: Plum ecoMAX (documentation, issues)
First occurred: 21:04:31 (1 occurrences)
Last logged: 21:04:31
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/plum_ecomax/config_flow.py", line 189, in async_step_device
    await self.device_task
  File "/config/custom_components/plum_ecomax/config_flow.py", line 175, in _wait_for_device
    self.device = await self.connection.get(ECOMAX, timeout=DEFAULT_TIMEOUT)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/event_manager.py", line 56, in get
    await self.wait_for(name, timeout=timeout)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/event_manager.py", line 43, in wait_for
    await asyncio.wait_for(self.create_event(name).wait(), timeout=timeout)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
```

### My diagnostics data:

![comm-setting](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/115409412/266b221d-93f0-4d80-b13b-37c53026edfe)
![serial-setting](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/115409412/240d184b-644c-4078-a482-c09c218a79e1)
![serial-state](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/115409412/e0ff5aed-6967-4f84-b5a6-b3a5e520151b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taziff** [comment]
Próbowałeś przełączyć D+ i D- do złącza G1?

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!

From your log I see that the integration did successfully connect to EW11, but didn't see any devices using EM protocol there and gave up.

Firstly, lets clarify that your specific device is a boiler controller, and not a heat pump, as this integration doesn't work with heat pumps.

Next please try to use settings for EW11 described [here](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/63#issuecomment-1884916946) and check your wiring. While in that specific case, the issue was, that device was in fact a heat pump with GM3 protocol, the settings themselves are correct.

**Comment by sundeveu** [comment]
> Próbowałeś przełączyć D+ i D- do złącza G1?

Właśnie to zrobiłem - niestety nic się nie zmieniło - nadal timeout i komunikat "Nie znaleziono żadnych urządzeń w sieci" 
Ale same połączenie do EW11 dociera bo pojawia się w statusie IP HA:
![status](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/115409412/96897390-4b6c-46da-ae09-f60c9732d056)
I po jakiś 2 minutach znika

Może jakiś problem z tym 810P3 - to piec Lazar Pellet Focus z 2017r

**Comment by denpamusic** [comment]
I believe that there's no pellet boilers that use GM3, protocol, especially not all the way back to 2017. So far we've only encountered it with heat pumps.

Also, although in different variant, I've seen EM810 working with this integration so your device should be compatible.

Did you try settings for EW11, that I've linked? Especially buffer size and gap time. EM can have pretty long messages, all the way up to 1000 bytes, while EW11 by default specifies 512 bytes buffer.

**Comment by sundeveu** [comment]
> Did you try settings for EW11, that I've linked? Especially buffer size and gap time. EM can have pretty long messages, all the way up to 1000 bytes, while EW11 by default specifies 512 bytes buffer.

Yes I did. I tried also other EW11 device (which I bought for connection to my solar panels inverter) and still no luck:
![4-integration](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/115409412/ed297a20-89e4-48e9-8cdb-4dd6d62ad61f)



Current running settings:
![1-comm](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/115409412/09a35fd2-2c71-4aef-b4c6-a99cb9997990)
![2-serial](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/115409412/eb2ba909-bcf9-4b4e-a138-c41e7c3b96b1)
Also I tried telnet connection to netp service @8899 - there is one character I receive:
![3-telnet](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/115409412/e0445362-bf35-4e11-b926-ca426b5a9a90)
I'll check one more thing: maybe 5V (measured: 4,85V) is not enough to power device - I will try with external 12V power supply.

**Comment by denpamusic** [comment]
> Also I tried telnet connection to netp service @8899 - there is one character I receive:

That doesn't look right for either EM or GM3 protocols. Did you try swapping D+ and D- around?

**Comment by sundeveu** [comment]
> That doesn't look right for either EM or GM3 protocols. Did you try swapping D+ and D- around?
Yes did it earlier and everything looks the same.

**Comment by Taziff** [comment]
Na G1 jest prędkość 115200 na G2 19600

**Comment by denpamusic** [comment]
Good. That at least tells us, that physical connection is working, although it really hard to understand anything in ASCII. Please wait until the weekend, I'll write you a script to grab data as hex string.

**Comment by sundeveu** [comment]
Thanks guys! 
Everything started to work after latest update to v0.4.2. I think update PyPlumIO to v0.5.15 solved problem.
![plum](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/115409412/305a770a-73cc-4ee8-b94b-bfa79af1f627)

**Comment by denpamusic** [comment]
That's great! Thanks for the heads up!

It's very interesting, that PyPlumIO (PIO) 0.5.15 solved the issue.
One of the greatest features of PIO v0.5.15 is insanely optimized main loop in frame producer. Up to 30% faster than previous implementation and doesn't waste any cycles during first iteration. Which leads me to think that maybe the issue, was somehow related to the PC used to run HASS, which is strange to think about, since HP t620 should be plenty powerful for the task, given that I'm running fine on Raspberry Pi 4B (8Gb version).

But, oh well, I'm very glad that you've got it to work!
Don't hesitate to contact me if any other issue arises.
