### ISSUE TITLE
See Mixer(s) information in HA

### ISSUE THREAD

**Issue by KaRLiKCZ** [denpamusic/homeassistant-plum-ecomax#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [ ] support for a new product
- [X] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

Hi,

Do you plan to access data from Mixer(s) in HA? Python library has it.
At the moment I has boiler with one mixer.

Thanks
Ondrej

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!

Yes, I plan to expose mixers and thermostats to HASS in the next major version of this integration (0.3.*).

My main problem with simply adding it as is in current branch is evergrowing amount of entities. Currently this integration adds 40 entities and adding mixers to the mix (pun intended😉) can increase this number by a lot.

So I'm implementing a way to select entities to add based on controller model and whether there are any mixers/thermostats connected to it.

If everything goes according to plan (i. e. no major issues found in underlying library), I expect to get this work done in about two weeks.

**Comment by KaRLiKCZ** [comment]
That sound perfect.

I'm ready to test it when it is out :) Hopefully will not be overloaded by house reconstruction in that time.

**Comment by KaRLiKCZ** [comment]
Hope everything go well :) Finger crossed 🤞

**Comment by KaRLiKCZ** [comment]
Hope everything go well. Finger crossed 🤞

**Comment by denpamusic** [comment]
It is going well, albeit a little bit slower than I anticipated😅

Actual implementations in both pyplumio and in hass integration are finished and, as far as I can tell, work pretty well.
Each mixer, that has temperature probe attached to it, will be treated as ecoMAX sub-device with own set of entities in hass.
This way we can avoid overcluttering controller page.

![2022-11-22](https://user-images.githubusercontent.com/16575433/203323747-a2ed036b-26b8-4b02-8af1-f317e54574d0.jpg)

For now only tests for hass integration are remaining.
As soon as I'm done with them, I'll make a release.

**Comment by denpamusic** [comment]
Hi,

Just a bit of heads up, thanks to a lot of great help from Aleksei (zASSAz), mixer controls should work now with integration version 0.2.26, but you may need to manually activate respective entities through UI.

With this I consider support for mixers as done.
There is a room for improvement still, and I'll probably add more features for the next major version. But for now, basic functionality should work in most cases.

Next up - thermostats😉
